version: '2'

services:

  node:
    container_name: api
    image: api
    build:
      context: ./api
    environment:
      - NODE_ENV=development
    volumes:
        - ./api:/var/www/nodeapp
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - nodeapp-network

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./mean-stack-crud-app
    environment:
      - NODE_ENV=development
    volumes:
        - ./mean-stack-crud-app:/var/www/frontend
    ports:
      - "4200:4200"
    networks:
      - nodeapp-network

  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
